image: ubuntu:jammy

stages:
  - build

compile:
  stage: build
  only:
    - tags
  script:
    - sed -i 's|http.*.ubuntu.com|http://mirrors.zju.edu.cn|' /etc/apt/sources.list
    - apt-get update && apt-get -y --no-install-recommends install ca-certificates build-essential fakeroot git dpkg-dev rpm python3 python-is-python3 python3-urllib3
    - mkdir artifacts
    - pushd build
    - ./build.sh
    - popd
    - cp build/debian/*.deb artifacts/
    - cp build/openwrt/*.opk artifacts/
    - cp build/rpm/*.rpm artifacts/
  artifacts:
    paths:
      - /artifacts

